apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base
- hpa.yaml

configMapGenerator:
- envs:
  - env
  name: ${CI_PROJECT_NAME}-configmap
  options:
    disableNameSuffixHash: true

namespace: tenpo-bo-transaction-orchestrator

patchesStrategicMerge:
- resources.yaml
